import { Row } from 'react-bootstrap';
import { useSelector } from 'react-redux';
import Bebida from './Bebida';

/**
 * The ListadoBebidas component renders a list of drinks using data from the Redux store.
 * @returns The ListadoBebidas component is returning a Row component with a list of Bebida components.
 * The list is generated by mapping over the drinks array and passing each drink object as a prop to
 * the Bebida component.
 */
const ListadoBebidas = () => {
  const { drinks } = useSelector((state) => state.drinks);

  return (
    <Row className="mt-4">
      {drinks.map((drink) => (
        <Bebida key={drink.idDrink} drink={drink} />
      ))}
    </Row>
  );
};

export default ListadoBebidas;
