import { createSlice } from '@reduxjs/toolkit';

/* The code is creating a Redux slice using the `createSlice` function from the `@reduxjs/toolkit`
library. A Redux slice is a collection of Redux-related functionality for a specific feature or
domain of your application. */
export const drinkSlice = createSlice({
  name: 'drink',
  initialState: {
    drinks: [],
    ingredient: [],
    categorias: [],
    isLoading: false,
  },
  reducers: {
    startLoading: (state) => {
      state.isLoading = true;
    },
    getCategorias: (state, { payload }) => {
      state.isLoading = false;
      state.categorias = payload.categoria;
    },
    getDrinks: (state, { payload }) => {
      state.isLoading = false;
      state.drinks = payload.drinks;
    },
    getDrinkById: (state, { payload }) => {
      state.isLoading = false;
      state.ingredient = payload.drink;
    },
  },
});

// Action creators are generated for each case reducer function
/* The line `export const { getDrinks, getDrinkById, getCategorias, startLoading } =
drinkSlice.actions;` is exporting the action creators generated by the `createSlice` function. */
export const { getDrinks, getDrinkById, getCategorias, startLoading } =
  drinkSlice.actions;
